# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YappHero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YappHero
  pod 'SnapKit'

  target 'YappHeroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YappHeroUITests' do
    # Pods for testing
  end

end
